In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("/home/florian/bachelorarbeit/code/Cross-Silo-FL/datasets/horizontal/covid/owid-covid-data.csv")

In [3]:
data.head()

iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          5.0        5.0   
1      AFG      Asia  Afghanistan  2020-02-25          5.0        0.0   
2      AFG      Asia  Afghanistan  2020-02-26          5.0        0.0   
3      AFG      Asia  Afghanistan  2020-02-27          5.0        0.0   
4      AFG      Asia  Afghanistan  2020-02-28          5.0        0.0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...   
1                 NaN           NaN         NaN                  NaN  ...   
2                 NaN           NaN         NaN                  NaN  ...   
3                 NaN           NaN         NaN                  NaN  ...   
4                 NaN           NaN         NaN                  NaN  ...   

   male_smokers  handwashing_facilities  hospital_beds_per_thousand  \
0           NaN                  37.746                         0.5   
1           NaN                  37.746                         0.5   
2           NaN                  37.746                         0.5   
3           NaN                  37.746                         0.5   
4           NaN                  37.746                         0.5   

   life_expectancy  human_development_index  population  \
0            64.83                    0.511  41128772.0   
1            64.83                    0.511  41128772.0   
2            64.83                    0.511  41128772.0   
3            64.83                    0.511  41128772.0   
4            64.83                    0.511  41128772.0   

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN   
1                                   NaN                          NaN   
2                                   NaN                          NaN   
3                                   NaN                          NaN   
4                                   NaN                          NaN   

   excess_mortality  excess_mortality_cumulative_per_million  
0               NaN                                      NaN  
1               NaN                                      NaN  
2               NaN                                      NaN  
3               NaN                                      NaN  
4               NaN                                      NaN  

[5 rows x 67 columns]

In [4]:

import sys
sys.path.insert(1, '../scripts')
import helper


In [11]:
x_train, x_test, y_train, y_test = helper.get_samples(data, 5, 0.3, ["total_cases", "new_cases"], "new_cases", helper.Dataset.Covid, max_samples=100)

In [12]:
x_test[0:5]

[array([ 80.,   6.,  91.,  11., 106.,  15., 114.,   8.]),
 array([11180.,   512., 11917.,   737., 12465.,   548., 13102.,   637.]),
 array([5., 0., 5., 0., 5., 0., 5., 0.]),
 array([1226.,   50., 1330.,  104., 1463.,  133., 1531.,   68.]),
 array([5339.,  372., 6053.,  714., 6402.,  349., 6635.,  233.])]

In [7]:
y_test[0:5]

[0.0, 643.0, 0.0, 172.0, 437.0]

In [6]:
len(x_train) + len(x_test)

100

*Scikit-Learn tests start here*

In [1]:
from sklearn.linear_model import LinearRegression

In [7]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [9]:
model.coef_

array([-5.19568947e-02,  7.84384789e-01, -7.51504499e-04,  5.12053902e-02,
       -2.17890899e-03, -1.42740449e-03,  5.03931323e-02,  5.25720413e-02])

In [10]:
model.intercept_

38.36728041998623

In [8]:
from sklearn.metrics import mean_squared_error

In [12]:
mean_squared_error(y_test, model.predict(x_test))

16984.464809532066

In [9]:
model.predict(x_test)

array([ 45.32492795, 553.67379447,  38.34480954,  95.56242226,
       416.93253183, 655.47572229,  40.97989437, 344.63513033,
       122.46405453, 740.20887929, 106.56487656, 660.02029654,
       312.15769324,  38.64022253,  38.34480954,  48.62964579,
        50.03879417,  44.31801192,  77.42718757,  38.34480954,
        81.19781601, 327.84188842,  38.34480954, 716.71020668,
        97.60723015,  88.4458933 ,  38.34480954, 732.74072544,
       577.32307506, 661.54705269])

In [6]:
new_model = LinearRegression()
hasattr(new_model, "coef_")

False